[package]
name = "day21_rs"
version = "0.1.0"
authors = ["Benjamin Congdon <bencongdon96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
lazy_static = "1.4.0"
itertools = "0.9.0"
